let student_alumni_list=[
    {
        student_alumni_name:"Pranit Patro",
        student_alumni_batch:"2017",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"JPMorgan Chase & Co.",
        student_alumni_feedback:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam labore accusamus a quisquam tenetur nobis! Lorem ipsum dolor sit amet.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1H4sGxkJmhE7i9nYC4WSnmDkffq9fFZ4Z",
    },
    {
        student_alumni_name:"Pranit",
        student_alumni_batch:"2017",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"JPMorgan Chase & Co.",
        student_alumni_feedback:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam labore accusamus a quisquam tenetur nobis! Lorem ipsum dolor sit amet.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1H4sGxkJmhE7i9nYC4WSnmDkffq9fFZ4Z",
    },
    {
        student_alumni_name:"Pranit",
        student_alumni_batch:"2017",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"JPMorgan Chase & Co.",
        student_alumni_feedback:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam labore accusamus a quisquam tenetur nobis! Lorem ipsum dolor sit amet.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1H4sGxkJmhE7i9nYC4WSnmDkffq9fFZ4Z",
    },
    {
        student_alumni_name:"Pranit",
        student_alumni_batch:"2017",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"JPMorgan Chase & Co.",
        student_alumni_feedback:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam labore accusamus a quisquam tenetur nobis! Lorem ipsum dolor sit amet.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1H4sGxkJmhE7i9nYC4WSnmDkffq9fFZ4Z",
    },
    {
        student_alumni_name:"Pranit",
        student_alumni_batch:"2017",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"JPMorgan Chase & Co.",
        student_alumni_feedback:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam labore accusamus a quisquam tenetur nobis! Lorem ipsum dolor sit amet.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1H4sGxkJmhE7i9nYC4WSnmDkffq9fFZ4Z",
    },
    {
        student_alumni_name:"Pranit",
        student_alumni_batch:"2017",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"JPMorgan Chase & Co.",
        student_alumni_feedback:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam labore accusamus a quisquam tenetur nobis! Lorem ipsum dolor sit amet.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1H4sGxkJmhE7i9nYC4WSnmDkffq9fFZ4Z",
    },
    {
        student_alumni_name:"Pranit",
        student_alumni_batch:"2017",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"JPMorgan Chase & Co.",
        student_alumni_feedback:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam labore accusamus a quisquam tenetur nobis! Lorem ipsum dolor sit amet.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1H4sGxkJmhE7i9nYC4WSnmDkffq9fFZ4Z",
    },
    {
        student_alumni_name:"Pranit",
        student_alumni_batch:"2017",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"JPMorgan Chase & Co.",
        student_alumni_feedback:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam labore accusamus a quisquam tenetur nobis! Lorem ipsum dolor sit amet.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1H4sGxkJmhE7i9nYC4WSnmDkffq9fFZ4Z",
    },
    {
        student_alumni_name:"Pranit",
        student_alumni_batch:"2017",
        student_alumni_course:"B.Tech",
        student_alumni_branch:"CSE",
        student_alumni_company_name:"JPMorgan Chase & Co.",
        student_alumni_feedback:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam labore accusamus a quisquam tenetur nobis! Lorem ipsum dolor sit amet.",
        student_alumni_added_date:"25-11-2023",
        student_img_id:"1H4sGxkJmhE7i9nYC4WSnmDkffq9fFZ4Z",
    },
    

]

export {student_alumni_list};